import type { AnswerFinalizer } from "@legalbuilder/legal-research-core"

type AnswerReceipt = ReturnType<AnswerFinalizer["receipt"]>
type AnswerCitation = AnswerReceipt["answer"]["citations"][number]

export function renderAnswerMarkdown(receipt: AnswerReceipt) {
  const { answer } = receipt
  const citations = [...answer.citations].sort(
    (left, right) => left.claimEnd - right.claimEnd || left.footnoteNumber - right.footnoteNumber,
  )
  const matter = receipt.matter.matter
  const lines = [
    "# Legal Research Answer",
    "",
    `**Matter:** ${literal(matter.name)}`,
    `**Jurisdiction:** ${literal(matter.jurisdiction)}`,
    `**Research as of:** ${literal(matter.researchAsOf)}`,
    `**Question:** ${literal(answer.question)}`,
    `**Answer status:** ${answer.sourceComplete ? "Source-complete" : "Verification required"}`,
    `**Answer ID:** \`${answer.id}\``,
    "",
    "## Answer",
    "",
    answerWithFootnotes(answer.text, citations),
    "",
    "## Footnotes",
    "",
  ]

  if (!citations.length) lines.push("No application-verified citations were attached to this answer.", "")
  for (const citation of citations) lines.push(...footnote(citation), "")

  lines.push(
    "## Provenance notice",
    "",
    "Footnote markers and provenance identifiers in this document were generated by the application after matter ownership, context admission, source availability, and passage hashes were checked. Text supplied by the model or a source is escaped and cannot create a footnote marker.",
    "",
    `The machine-readable sidecar is \`${answer.id}-answer-receipt.json\` (contract version ${receipt.contractVersion}).`,
    `This readable export was generated at ${receipt.exportedAt}.`,
    "",
  )
  return `${lines.join("\n")}\n`
}

function answerWithFootnotes(text: string, citations: AnswerCitation[]) {
  let cursor = 0
  const rendered: string[] = []
  for (const citation of citations) {
    if (citation.claimEnd < cursor || citation.claimEnd > text.length) throw new Error("Invalid citation offset")
    rendered.push(literal(text.slice(cursor, citation.claimEnd)), `[^${citation.footnoteNumber}]`)
    cursor = citation.claimEnd
  }
  rendered.push(literal(text.slice(cursor)))
  return rendered.join("")
}

function footnote(citation: AnswerCitation) {
  const lines = [
    `[^${citation.footnoteNumber}]: **${titleCase(citation.status)} claim.** ${literal(citation.claimText)}`,
    `    Citation \`${citation.citationId}\`; claim \`${citation.claimId}\`.`,
  ]
  for (const [index, evidence] of citation.evidence.entries()) {
    lines.push(
      `    ${index + 1}. **${titleCase(evidence.relationship)} — ${literal(evidence.sourceTitle)}**`,
      `       Source version \`${evidence.sourceVersionId}\`; passage \`${evidence.passageId}\`; text SHA-256 \`${evidence.textSha256}\`.`,
      `       Location: ${location(evidence)}. Verification: ${evidence.verificationState}.`,
      evidence.text === null
        ? "       Exact passage unavailable; use the JSON receipt to inspect the recorded verification state."
        : `       Exact passage: “${literal(evidence.text).replaceAll("\n", "\n       ")}”`,
    )
  }
  return lines
}

function location(evidence: AnswerCitation["evidence"][number]) {
  if (evidence.locationMode !== "coordinates" || evidence.pageNumber === null || !evidence.bbox)
    return "structural fallback"
  const { left, top, right, bottom } = evidence.bbox
  return `page ${evidence.pageNumber}, box ${left},${top},${right},${bottom}`
}

function literal(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replace(/([\\`*_[\]{}()#+.!|-])/g, "\\$1")
}

function titleCase(value: string) {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`
}
